#!/usr/bin/env python3
"""Sync DSH plugin skill assets from the repository's authoritative skills/.

Mirrors every skills/<name> bundle into the DSH plugin package's
assets/skills/ directory, excluding the Claude/Codex-specific agents/
directory, and regenerates lib/skills.generated.js from each SKILL.md
frontmatter. The generated assets are committed, so installing the package
needs no build step (DeepSeek Harness blocks git-hosted prepare scripts until
explicitly allowed; committing the mirrors sidesteps that entirely).

Read-only by default (checks for drift, like sync_shared_files.py); pass
--write to refresh the mirrors and the manifest.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[2]
SKILLS_SOURCE_NAME = "skills"
PACKAGE_DIR_NAME = Path("packages") / "dsh-build-goals"
ASSETS_RELATIVE = Path("assets") / "skills"
MANIFEST_RELATIVE = Path("lib") / "skills.generated.js"

NAME_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
TOP_LEVEL_FIELD = re.compile(r"^([a-z0-9-]+):\s*(.*)$")
EXCLUDED_DIRS = {"agents", "__pycache__", ".git"}
EXCLUDED_FILES = {".DS_Store"}
BOOL_VALUES = {
    "true": True,
    "yes": True,
    "on": True,
    "1": True,
    "false": False,
    "no": False,
    "off": False,
    "0": False,
}

MANIFEST_HEADER = (
    "// Generated by scripts/sync_skills.py — do not edit by hand.\n"
    "// Authoritative source: skills/ in the build-goals repository root.\n"
    "// Regenerate with: python3 packages/dsh-build-goals/scripts/sync_skills.py"
    " --root . --write\n"
)


class SyncError(RuntimeError):
    """Raised when the mirror contract is invalid or unsafe."""


def parse_frontmatter(skill_md: Path) -> dict[str, str]:
    """Extract top-level frontmatter fields from a SKILL.md file."""
    try:
        lines = skill_md.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError) as exc:
        raise SyncError(f"无法读取 SKILL.md：{skill_md}") from exc
    if not lines or lines[0].strip() != "---":
        raise SyncError(f"SKILL.md 缺少起始 Frontmatter 分隔符：{skill_md}")
    closing = next(
        (index for index in range(1, len(lines)) if lines[index].strip() == "---"),
        None,
    )
    if closing is None:
        raise SyncError(f"SKILL.md 缺少结束 Frontmatter 分隔符：{skill_md}")

    fields: dict[str, str] = {}
    for line in lines[1:closing]:
        match = TOP_LEVEL_FIELD.match(line)
        if match:
            fields[match.group(1)] = match.group(2).strip()
    return fields


def invocation_bool(
    fields: dict[str, str],
    field: str,
    default: bool,
    skill_md: Path,
) -> bool:
    """Parse a DSH invocation field; fail closed on malformed values.

    The DeepSeek Harness filesystem provider drops a whole skill when an
    invocation value is not a recognized boolean, so the mirror must refuse to
    generate a manifest it could not load.
    """
    raw = fields.get(field)
    if raw is None or raw == "":
        return default
    key = raw.lower()
    if key not in BOOL_VALUES:
        raise SyncError(f"{skill_md} 的 {field} 不是可识别的布尔值：{raw}")
    return BOOL_VALUES[key]


def skill_entries(source_skills: Path) -> list[dict]:
    """Collect the generated manifest entries for every bundled skill."""
    entries: list[dict] = []
    for skill_dir in sorted(path for path in source_skills.iterdir() if path.is_dir()):
        name = skill_dir.name
        if not NAME_PATTERN.fullmatch(name):
            raise SyncError(f"Skill 目录名不符合 kebab-case：{skill_dir}")
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            raise SyncError(f"缺少 SKILL.md：{skill_dir}")

        fields = parse_frontmatter(skill_md)
        if fields.get("name") != name:
            raise SyncError(
                f"SKILL.md 的 name 与目录名不一致：{skill_md}（{fields.get('name')}）"
            )
        description = fields.get("description")
        if not description:
            raise SyncError(f"SKILL.md 缺少 description：{skill_md}")

        model_invocable = not invocation_bool(
            fields, "disable-model-invocation", False, skill_md
        )
        user_invocable = invocation_bool(fields, "user-invocable", True, skill_md)
        entries.append(
            {
                "name": name,
                "description": description,
                "modelInvocable": model_invocable,
                "userInvocable": user_invocable,
            }
        )
    if not entries:
        raise SyncError(f"技能源目录为空：{source_skills}")
    return entries


def render_manifest(entries: list[dict]) -> str:
    body = ",\n".join(
        "  " + json.dumps(entry, ensure_ascii=False) for entry in entries
    )
    return MANIFEST_HEADER + f"export const SKILLS = [\n{body},\n];\n"


def mirror_ignorer(source_dir: Path, names: list[str]) -> set[str]:
    del source_dir
    ignored = set(EXCLUDED_DIRS)
    ignored.update(name for name in names if name in EXCLUDED_FILES)
    return ignored


def is_mirrored(relative: str) -> bool:
    """Whether a source path participates in the committed asset mirror."""
    parts = Path(relative).parts
    return not (
        parts[0] == "agents"
        or any(part in EXCLUDED_DIRS for part in parts)
        or parts[-1] in EXCLUDED_FILES
    )


def tree_digest(root: Path) -> dict[str, str]:
    """Map every relative file path under root to its SHA-256 digest."""
    digest: dict[str, str] = {}
    if not root.is_dir():
        return digest
    for path in sorted(root.rglob("*")):
        if path.is_file():
            relative = path.relative_to(root).as_posix()
            digest[relative] = hashlib.sha256(path.read_bytes()).hexdigest()
    return digest


def write_mirrors(source_skills: Path, assets_root: Path) -> None:
    if assets_root.exists():
        shutil.rmtree(assets_root)
    assets_root.mkdir(parents=True)
    for skill_dir in sorted(path for path in source_skills.iterdir() if path.is_dir()):
        shutil.copytree(
            skill_dir,
            assets_root / skill_dir.name,
            symlinks=False,
            ignore=lambda directory, names: mirror_ignorer(skill_dir, names),
        )


def sync(root: Path, *, write: bool) -> bool:
    """Check the mirrors against the authoritative source, or refresh them.

    Returns True when the committed assets already match the source.
    """
    source_skills = root / SKILLS_SOURCE_NAME
    if not source_skills.is_dir():
        raise SyncError(f"找不到技能源目录：{source_skills}")
    package_dir = root / PACKAGE_DIR_NAME
    assets_root = package_dir / ASSETS_RELATIVE
    manifest_path = package_dir / MANIFEST_RELATIVE

    entries = skill_entries(source_skills)
    expected_manifest = render_manifest(entries)

    if write:
        write_mirrors(source_skills, assets_root)
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(expected_manifest, encoding="utf-8")
        print(f"已同步 {len(entries)} 个 Skill 到 {assets_root}")
        return True

    problems: list[str] = []
    source_digest = tree_digest(source_skills)
    assets_digest = tree_digest(assets_root)
    mirrored_source = {
        relative: digest
        for relative, digest in source_digest.items()
        if is_mirrored(relative)
    }

    for relative in sorted(set(mirrored_source) | set(assets_digest)):
        if mirrored_source.get(relative) != assets_digest.get(relative):
            problems.append(f"资产漂移：{relative}")

    try:
        current_manifest = manifest_path.read_text(encoding="utf-8")
    except OSError:
        current_manifest = ""
    if current_manifest != expected_manifest:
        problems.append("清单漂移：lib/skills.generated.js 与 skills/ 不一致")

    if problems:
        print("DSH 插件包资产与 skills/ 不一致：", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        print("确认修改后重新执行并添加 --write。", file=sys.stderr)
        return False

    print(f"DSH 插件包资产与 skills/ 一致（{len(entries)} 个 Skill）。")
    return True


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="只读检查或显式同步 DSH 插件包的 Skill 镜像资产。"
    )
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT, help="仓库根目录")
    parser.add_argument("--write", action="store_true", help="刷新镜像资产与清单")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    try:
        return 0 if sync(args.root.expanduser().resolve(), write=args.write) else 1
    except (SyncError, OSError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
